### ISSUE TITLE
High Availability with an External DB with CockroachDB

### ISSUE THREAD

**Issue by alifpay** [k3s-io/kine#79] opened 2021-03-12 10:54 UTC
starting kubernetes: preparing server: creating storage endpoint: building kine: storage backend is not defined

CockroachDB is supports lib/pq driver, but k3s is not running with CockroachDB

**Comment by brandond** [comment] 2021-03-12 21:18
Duplicate of #76 and k3s-io/k3s#3056

**Closed by brandond** 2021-03-12 21:18 UTC
